apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tomcat-test
    spec:
      containers:
      - name: tomcat-test 
        image: tomcat-test 
        imagePullPolicy: Never  
