apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-test
  template:
    metadata:
      labels:
        app: tomcat-test
    spec:
      containers:
      - name: tomcat-test 
        image: tomcat-test 
        imagePullPolicy: Never  
