apiVersion: v1
kind: Service
metadata:
  name: tomcat-test
  labels:
    app: tomcat-test
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 32667
    targetPort: 8080
  selector:
    name: tomcat-test
